apiVersion: v1
kind: Deployment
metadata:
  name: poi
  namespace: insurance-api
  labels:
    app: poi
spec:
  selector: 
    matchLabels: 
      app: poi
  template:
    metadata:
      labels: 
        app: poi
    spec:
      containers:
      - name: poi
        image: registrykua3387.azurecr.io/poi
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 200Mi
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_PASSWORD
        - name: SQL_SERVER
          value: "sqlserverkua3387.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Local"
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: insurance-api
spec:  
  selector:
    app: poi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer