apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: insurance-api
spec:
  containers:
    - name: userprofile
      image: registrykua3387.azurecr.io/userprofile
      imagePullPolicy: IfNotPresent