kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-role
  namespace: insurance-web
#rules:
#- apiGroups: ["", "extensions", "apps"]
#  resources: ["*"]
#  verbs: ["*"]
#- apiGroups: ["batch"]
#  resources:
#  - jobs
#  - cronjobs
#  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-role-binding
  namespace: insurance-web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev-role
subjects:
- kind: Group
  namespace: insurance-web
#  name: groupObjectId
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-role
  namespace: insurance-web
#rules:
#- apiGroups: ["", "extensions", "apps"]
#  resources: ["*"]
#  verbs: ["*"]
#- apiGroups: ["batch"]
#  resources:
#  - jobs
#  - cronjobs
#  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-role-binding
  namespace: insurance-web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-role
subjects:
- kind: Group
  namespace: insurance-web
#  name: groupObject