kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-role
  namespace: insurance-api
#rules:
#- apiGroups: ["", "extensions", "apps"]
#  resources: ["*"]
#  verbs: ["*"]
#- apiGroups: ["batch"]
#  resources:
#  - jobs
#  - cronjobs
#  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-role-binding
  namespace: insurance-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev-role
subjects:
- kind: Group
  namespace: insurance-api
  name: c18bc486-3769-4abe-b37b-72cca3fd7c55
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-role
  namespace: insurance-api
#rules:
#- apiGroups: ["", "extensions", "apps"]
#  resources: ["*"]
#  verbs: ["*"]
#- apiGroups: ["batch"]
#  resources:
#  - jobs
#  - cronjobs
#  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-role-binding
  namespace: insurance-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-role
subjects:
- kind: Group
  namespace: insurance-api
  name: b113fe3f-98c5-4070-a2b2-f0719adad3be