apiVersion: v1
kind: Secret
metadata:
  namespace: insurance-api
  name: sql-secret
type: Opaque
stringData:
<<<<<<< HEAD
  SQL_USER: sqladminoMj3031
  SQL_PASSWORD: eaZYSLfuNsLSvgVH/i1huXMZ9Va59K4S
=======
  SQL_USER: sqladminkUa3387
  SQL_PASSWORD: rO7xp7Lw9
>>>>>>> 79a95cc8caaf5fa9ca5fd3d2938e309f13f36d0c
