apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: insurance-api
  labels:
    app: tripviewer
spec:
  selector: 
    matchLabels: 
      app: tripviewer
  template:
    metadata:
      labels: 
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrykua3387.azurecr.io/tripviewer
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile-service:80"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-service:80"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: insurance-api
spec:  
  selector:
    app: tripviewer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer
