apiVersion: v1
kind: Deployment
metadata:
  name: Trips
  namespace: insurance-api 
spec:
  containers:
    - name: trips
      image: registrykua3387.azurecr.io/trips
      imagePullPolicy: IfNotPresent