apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: insurance-api 
  labels:
    app: trips
spec:
  selector: 
    matchLabels: 
      app: trips
  template:
    metadata:
      labels: 
        app: trips
    spec:
      containers:
      - name: trips
        image: registrykua3387.azurecr.io/trips
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: SQL_PASSWORD
        - name: SQL_SERVER
          value: "sqlserverkua3387.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"

---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: insurance-api
spec:  
  selector:
    app: trips
  ports:
  - protocol: TCP
    port: 80
  type: ClusterIP
